### ISSUE TITLE
Connection refused on Philips TV 55PUK7150/12 with Android TV 5.1

### ISSUE THREAD

**Issue by Slion** [LeonNicholls/Anymote-for-Java#2]
Somehow I can't connect to my Android TV even though the Play Store Android TV application works just fine. Looking at captured network packets for Android TV application I can see it is talking to that same IP but on ports 6466 and 6467. Tried specifying both those ports but that did not help. I tried disabling firewall, that did not help either. Any suggestions would be most welcome.

```
Finding devices...
Jul 12, 2016 4:25:15 PM com.entertailion.java.anymote.util.Log i
INFO: TvDiscoveryService: Enabling broadcast
Jul 12, 2016 4:25:15 PM com.entertailion.java.anymote.util.Log i
INFO: BroadcastDiscoveryClient: Starting client on address /192.168.178.255
Jul 12, 2016 4:25:15 PM com.entertailion.java.anymote.util.Log i
INFO: BroadcastDiscoveryClient: Broadcast client thread starting.
Jul 12, 2016 4:25:18 PM com.entertailion.java.anymote.util.Log i
INFO: TvDiscoveryService: Disabling broadcast
Jul 12, 2016 4:25:18 PM com.entertailion.java.anymote.util.Log i
INFO: BroadcastDiscoveryClient: Exiting client loop.
1: Manual IP address
Enter choice: 1
Enter IP address: 192.168.178.82
Attempting to connecting to Secure: GTV device [/192.168.178.82:9551]
Jul 12, 2016 4:25:37 PM com.entertailion.java.anymote.util.Log e
SEVERE: ConnectingActivity: (IOE) Could not create socket to GTV device
java.net.ConnectException: Connection refused: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.<init>(Unknown Source)
    at sun.security.ssl.SSLSocketFactoryImpl.createSocket(Unknown Source)
    at com.entertailion.java.anymote.connection.ConnectingTask.attemptToConnect(ConnectingTask.java:360)
    at com.entertailion.java.anymote.connection.ConnectingTask.connect(ConnectingTask.java:203)
    at com.entertailion.java.anymote.connection.ConnectingTask.run(ConnectingTask.java:175)

Jul 12, 2016 4:25:38 PM com.entertailion.java.anymote.util.Log e
SEVERE: ConnectingActivity: Failed to connect
java.net.ConnectException: Connection refused: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at java.net.Socket.<init>(Unknown Source)
    at java.net.Socket.<init>(Unknown Source)
    at com.entertailion.java.anymote.connection.ConnectingTask.attemptToPair(ConnectingTask.java:260)
    at com.entertailion.java.anymote.connection.ConnectingTask.connect(ConnectingTask.java:209)
    at com.entertailion.java.anymote.connection.ConnectingTask.run(ConnectingTask.java:175)

Jul 12, 2016 4:25:38 PM com.entertailion.java.anymote.util.Log i
INFO: ConnectingActivity: Pairing failed
Jul 12, 2016 4:25:38 PM com.entertailion.java.anymote.util.Log e
SEVERE: ConnectingActivity: run
java.lang.NullPointerException: null socket
    at com.entertailion.java.anymote.client.AnymoteSender.attemptToConnect(AnymoteSender.java:118)
    at com.entertailion.java.anymote.connection.ConnectingTask.run(ConnectingTask.java:177)

Connection failed

```

**Comment by mtthsfrdrch** [comment]
Anymote is the remote protocol used by GoogleTV back then. Although AndroidTV (!= GoogleTV) seems to be using some sort of very similar successor of Anymote, it's sadly not compatible anymore and so far Google didn't release any documentation for the new protocol yet. So yeah, it's either reverse engineering it (which i guess is quite a pile of work to do) or waiting for Google to release something.

**Comment by Slion** [comment]
Thanks, I've since realized that myself. Really disappointing to see Google stepping back like that.
It's not like TVs are any more secure for it. I'll go for an IR blasting solution I guess.

**Comment by Slion** [comment]
To some extent you can also use HDMI CEC to control your Android TV.
